# Info
title: Inyestar
description: Inyestar Blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://inyestar.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Theme
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true
