# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Inyestar
tagline:          'Blog'
description:      'Beyond infinity!'
url:              https://inyestar.github.io
baseurl:          https://inyestar.github.io

author:
  name:           'Inyestar'
  url:            https://github.com/inyestar
  email:          yuinye@gmail.com

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/inyestar

linkedin:
  repo:           https://www.linkedin.com/in/inye-yu-990429149/

plugins:          [jekyll-paginate]